### ISSUE TITLE
Add bindings for all the TextViews to FragmentCalibrate.java and all the bindings to FragmentAnalyze.java

### ISSUE THREAD

**Issue by tgibbons-css** [CIS-Gibbons-Research/CEC_Prototype_2#10]
Add rest of the bindings to FragmentCalibrate.java

        tvCalibrate1 = binding.textViewCalibrate1;
        // TODO -- Add bindings for rest of the textview.

Declare TextViews and set up bindings in FragmentAnalyze to mirror those in FragmentCalibrate
Also add button declarations and binds to  FragmentAnalyze to mirror those in FragmentCalibrate

**Comment by hharrari** [comment]
Added rest of bindings for textview and button.
