### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by zmurphy1** [CIS-Gibbons-Research/CEC_Prototype_2#13]
There are unit tests written for a few of our classes, but it is best practice to try and write a unit test for every class / or where we are actually doing functionality code. The only class that we have unit tests for right now is the LinearRegression.java class. I think any class that is attempting an advanced get call or a method that is retrieving data should have a test class!

**Comment by milesliebren** [comment]
None of the unit tests compile, @zmurphy1.

They all require mock dependencies, which aren't in the current gradle script. ARGB_8888 is deprecated.

Bitmap.Config config = Bitmap.Config.ARGB_8888;

**Comment by milesliebren** [comment]
https://www.geeksforgeeks.org/unit-testing-in-android-using-mockito/#

**Comment by milesliebren** [comment]
We need to change ChemicalAnalysisTest to run with a mock context because it currently has a null context.

**Comment by milesliebren** [comment]
All unit tests have been modified and now work, except chemicalAnalysisTest, which will be a separate issue.
