### ISSUE TITLE
Convert region coordinates into percentage of whole image

### ISSUE THREAD

**Issue by tgibbons-css** [CIS-Gibbons-Research/CEC_Prototype_2#18]
The coordinates in regions.xml are based on the original full-sized images which were 3024 x 4032 pixels.  I think when we read in the images they bitmaps maybe resized. Also, in the future we may take photos at a different resolution.

So, the bounding box coordinates for each region should be changed to a percentage of the full image.  This format is often falled YOLO-5 after the ML model that popularized it.  See C[onvert bounding boxes from Coco to Pascal_VOC to Yolo and back.](https://christianbernecker.medium.com/convert-bounding-boxes-from-coco-to-pascal-voc-to-yolo-and-back-660dc6178742).  Note, when the writer says the YOLO uses "normalized" values these are percentages becasuse we normalize the coordinates to the range 0.0 - 1.0.

So, we should update the data in regions.xml to be normalized or percentages of the full image.  We can then convert these to matach any sized BitMap in our code.

I have highlighted these percentages in green on the second tab of our [Research Circle Coordinates](https://docs.google.com/spreadsheets/d/1_PH6tL9P7985-t8v0ckNZNi2XEL_QrH36wXYgKktfjw/edit?usp=sharing) sheet.

**Comment by milesliebren** [comment]
Need to finish #13 and #21 to test this functionality. This commit addresses the problem, but cannot be tested until those 2 issues are closed.

**Comment by milesliebren** [comment]
Closed last week, #13 and #21 were closed.
