### ISSUE TITLE
Create Unit Test class For ChemicalAnalysis class

### ISSUE THREAD

**Issue by zmurphy1** [CIS-Gibbons-Research/CEC_Prototype_2#23]
Write unit tests for methods that will be returning data inside of the chemical analysis class. 

To create a unit test in android studio press on the class name inside of the class then press go to then press test class!

**Comment by milesliebren** [comment]
@zmurphy1 @beeecer I'd like #13 (other unit tests) to be functional before we test this class. We need to be able to create test mock bitmaps.
