### ISSUE TITLE
Manual camera settings

### ISSUE THREAD

**Issue by tgibbons-css** [CIS-Gibbons-Research/CEC_Prototype_2#26]
Move the manual camera settings from [CEC_Camers2_Test1 ](https://github.com/CIS-Gibbons-Research/CEC_Camera2_Test1/blob/master/app/src/main/java/css/chem/project/SensorCam2.java)over to the SensorCamera class. 

This may be more complicated since SensorCam2 uses the older Android Camera2 library and SensorCamera uses the newest Android CameraX library.  Hopefully there is someway to do these older manual settings in CameraX..

It looks like you can do the setting with this code, but I could not get it to compile without errors:
```
        // Set camera parameters
        Camera2Interop.Extender<ImageCapture> extender = new Camera2Interop.Extender<>(imageCapture);
        extender.setCaptureRequestOption(CaptureRequest.SENSOR_SENSITIVITY, 1600);
```

These are the basic setting we need:
```
    captureBuilder.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_OFF);             // set to manual flash control
    captureBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_OFF);                       // set flash off
	captureBuilder.set(CaptureRequest.CONTROL_AE_EXPOSURE_COMPENSATION, 0);                             // set
    captureBuilder.set(CaptureRequest.LENS_FOCUS_DISTANCE, 10.5f);                                    // set focal distance
    captureBuilder.set(CaptureRequest.LENS_FOCAL_LENGTH, 4.38f);                                            // set
    captureBuilder.set(CaptureRequest.SENSOR_SENSITIVITY, 600);                                       // set ISO sensitivity
    captureBuilder.set(CaptureRequest.SENSOR_EXPOSURE_TIME, 66600000L);                               // 66600000 nanoseconds is 1/15sec
```

**Comment by milesliebren** [comment]
Unfortunately, some settings we're trying to apply, such as LENS_FOCUS_DISTANCE and LENS_FOCAL_LENGTH, are not directly available in the CameraX API.
