### ISSUE TITLE
Calibration Readings for ChemicalAnalysis.doCalibration() are all 0.0

### ISSUE THREAD

**Issue by milesliebren** [CIS-Gibbons-Research/CEC_Prototype_2#7]
Intensity extractor values might be wrong, causing all of the values for "calibrationIntensities" to be 0.0.

Current logcat when sample_image_a is passed to .takePhoto() - regions are correctly passed, but the intensity is always 0.

.takePhoto(): Standard Bitmap H: 11088 | Standard Bitmap W: 8316
.doCalibration(): Calibration Bitmap H: 11088 | Calibration Bitmap W: 8316
D  xUL, yUL, xWid, yHeight, rad: 1560, 931, 332, 332, 166
D  xUL, yUL, xWid, yHeight, rad: 1718, 1201, 350, 350, 175
D  xUL, yUL, xWid, yHeight, rad: 1549, 1615, 350, 350, 175
D  xUL, yUL, xWid, yHeight, rad: 1174, 1627, 326, 326, 163
D  xUL, yUL, xWid, yHeight, rad: 1027, 1331, 312, 312, 156
D  xUL, yUL, xWid, yHeight, rad: 1146, 1013, 314, 314, 157
D  Fluorescence values size: 6
D  Concentration values size: 6
D  Adding in x = 0.0 and y = 0.1
D  Adding in x = 0.0 and y = 0.3
D  Adding in x = 0.0 and y = 0.5
D  Adding in x = 0.0 and y = 0.7
D  Adding in x = 0.0 and y = 0.9
D  Adding in x = 0.0 and y = 1.0

**Comment by milesliebren** [comment]
if the height is 11,000px and the width is 8,300px, our regions are off, causing the problem.

**Comment by milesliebren** [comment]
this means we need to crop the image in the SensorCamera class:

// TODO: add code to crop to just the needed area of the photo
                //bitmap = Bitmap.createBitmap(bitmap, rect.left, rect.top, rect.width(), rect.height())

**Comment by zmurphy1** [comment]
@milesliebren Should we be assuming that the regions will be in the same place every time though? Or should we try and make some method that checks for the regions placement?

**Comment by milesliebren** [comment]
@zmurphy1 We assumed that the image would be cropped so that the regions would be in the same place every time. A region-finder method wouldn't be a bad idea in RegionFinder.java, but cropping seems easier. @tgibbons-css and @beeecer do you have any thoughts?
